### ISSUE TITLE
Using base href breaks footnotes

### ISSUE THREAD

**Issue by j605** [gyorb/hugo-dusk#21]
For further reference, see https://github.com/gohugoio/hugo/issues/811 and https://discourse.gohugo.io/t/footnote-problems-with-markdown/504/2

**Comment by giordi91** [comment]
any news on this? I am currently facing the same problem, not really sure how to work around it.

**Comment by gyorb** [comment]
I've created a fix for it, let me know if it works for you too.

**Comment by j605** [comment]
It works for me, thanks. Although you might want to fix the typo in the commit message :)
