### ISSUE TITLE
footnote anchors

### ISSUE THREAD

**Issue by BloggerBust** [gyorb/hugo-dusk#23]
Hi,

Firstly, I want you to know that I really like this theme. Thank you for maintaining it.

I have run into one issue, but it may not be an issue with your theme. I am using [org-mode footnotes](http://orgmode.org/manual/Footnotes.html) and the anchors are linking to the home page rather than the post that they are linked from / to. I read the section on [links and cross references](https://gohugo.io/content-management/cross-references/#hugo-heading-anchors) and it suggests that the anchor should be exported with the pages unique identifier, but when I inspect the element I can see that the anchor has no unique identifier. Since it is missing the unique identifier I started to wonder if it is perhaps an issue with the theme, but I have no idea. Have you tried using footnotes? Do you know how to make org-mode footnotes work as expected?

I am currently using hugo v0.46

You time is appreciated.

**Comment by BloggerBust** [comment]
Whatever the issue is it is definitely not an issue with your theme. I started a [discussion on the gohugo discourse forum](https://discourse.gohugo.io/t/org-mode-anchors/13842/10) and am closing this issue.

**Comment by gyorb** [comment]
@BloggerBust I've just fixed the problem a few days ago see issue #21 and the corresponding change #22 if you use the master branch with the latest changes it should work.
Let me know if you still experience some problems with it.

**Comment by BloggerBust** [comment]
Hi gyorb,

Thank you very much for fixing this issue. Your time on this is appreciated. I have pulled from your master branch and everything is working as expected now.

Cheers!
